name: Calculadora-action

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Nos logueamos en DockerHub
    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    # Creamos la imagen y le agregamos un tag
    - name: Build and tag Docker image
      run: docker build -t pabloagustinm/calculadora:uploadAuto .

    # Subimos la imagen a DockerHub
    - name: Push Docker image to DockerHub
      run: docker push pabloagustinm/calculadora:uploadAuto
